FROM quay.io/singlecellpipelinetest/miniconda3:4.10.3
ADD . /app

RUN apt-get update -y && apt-get install -y libltdl7 parallel && rm -rf /var/lib/apt/lists/*

RUN conda install --file /app/conda_requirements.yml

RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.6.3
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@{git_commit}
RUN pip install azure-batch azure-common azure-core azure-storage-blob azure-identity
