FROM quay.io/singlecellpipelinetest/miniconda3:4.8.2
ADD . /app
RUN conda install --file /app/conda_requirements.yml

RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.6.0
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@{git_commit}
RUN pip install git+https://github.com/shahcompbio/cell_cycle_classifier.git@v0.0.3
RUN pip install azure-batch azure-common azure-core azure-storage-blob azure-identity
