version: 0.2

phases:
  pre_build:
    commands:
      - bash single_cell/tests/jenkins/build_docker_staging/build.sh $DOCKERHUB_USR $DOCKERHUB_PSW docker.io singlecellpipelinetest
  build:
    commands:
      - bash single_cell/tests/jenkins/refdata/download.sh
      - bash single_cell/tests/jenkins/align/align.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/hmmcopy/hmmcopy.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/annotation/annotation.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/merge_cell_bams/merge_cell_bams.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/split_wgs_bam/split_wgs_bam.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/variant_calling/variant_calling.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/breakpoint_calling/breakpoint_calling.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/infer_haps/infer_haps.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/count_haps/count_haps.sh singlecellpipelinetest
      - bash single_cell/tests/jenkins/pseudo_bulk_qc/pseudo_bulk_qc.sh  singlecellpipelinetest
