package:
  name: single_cell_pipeline
  version: '0.5.15'

source:
  git_url: https://github.com/shahcompbio/single_cell_pipeline.git
  git_rev: v0.5.15

build:
  number: 4

requirements:
  build:
    - python

  run:
    - python
    - intervaltree
    - matplotlib
    - pypdf2
    - pypeliner
    - pysam
    - python-dateutil
    - pyvcf
    - pyyaml
    - seaborn
    - statsmodels
    - scikit-learn
    - jsonpickle
about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'

