# build on top of out base image
FROM singlecellpipeline/python_singlecell_qc:v0.1.2

ADD . /app

# Copy the current directory contents into the container at /app

# Install any needed packages specified in requirements.txt
RUN pip install -e git+https://github.com/shahcompbio/pypeliner.git@v0.5.18#egg=pypeliner
RUN pip install -e git+https://github.com/shahcompbio/biowrappers.git@v0.2.8#egg=biowrappers
RUN cd /app && python setup.py install

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME scpipeline

# Run app.py when the container launches
CMD ["python"]
