# build on top of out base image
FROM singlecellpipeline/python_singlecell_qc:v0.1.3

ADD . /app

# Copy the current directory contents into the container at /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install libc-dev libz-dev -y && apt-get install build-essential -y && rm -rf /var/lib/apt/lists/*
RUN pip install -e git+https://github.com/shahcompbio/pypeliner.git@v0.5.23#egg=pypeliner
RUN pip install -e git+https://github.com/shahcompbio/biowrappers.git@v0.2.8#egg=biowrappers
RUN pip install -e git+https://github.com/shahcompbio/scgenome.git@master#egg=scgenome
RUN pip install -e git+https://github.com/amcpherson/wgs_analysis.git@master#egg=wgs_analysis
RUN cd /app && python setup.py install
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME scpipeline

# Run app.py when the container launches
CMD ["python"]
