FROM continuumio/miniconda3:4.8.2

ADD . /app
RUN conda install --file /app/requirements.yml

RUN rm -rf /opt/conda/lib/python2.7/site-packages/remixt* && apt-get update && apt install libc-dev libz-dev build-essential -y && rm -rf /var/lib/apt/lists/* && conda install -c bioconda cython

RUN pip install git+https://github.com/shahcompbio/pypeliner.git@master
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@{git_commit}
#RUN pip install numpy==1.19.5 pandas==0.25.3 --force-reinstall
