package:
  name: single_cell_pipeline_hmmcopy
  version: '0.6.19'

source:
  git_url: https://github.com/shahcompbio/single_cell_pipeline.git
  git_rev: v0.6.19

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - matplotlib
    - pandas=0.25.3
    - pypdf2
    - pypeliner
    - pysam
    - pyvcf
    - pyyaml
    - seaborn
    - statsmodels
    - scikit-learn
    - ete3
    - bioconductor-hmmcopy-single-cell
about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'

