# build on top of out base image
FROM shahlab.azurecr.io/scp/python_singlecell_qc:v0.0.1

# Set the working directory to /app
#WORKDIR /datadrive/singlecell/docker/app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install git+https://dgrewal@bitbucket.org/dranew/pypeliner.git@master
RUN pip install git+https://bitbucket.org/aroth85/biowrappers.git@singlecell
RUN cd /app && python setup.py install
# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME scpipeline

# Run app.py when the container launches
CMD ["single_cell"]
