package:
  name: single_cell_pseudo_bulk_qc
  version: '0.6.22'
source:
  - git_url: https://github.com/shahcompbio/single_cell_pipeline.git
    git_rev: v0.6.22
    folder: single_cell_pipeline
  - git_url: https://github.com/shahcompbio/pypeliner.git
    git_rev: v0.5.20
    folder: pypeliner
  - git_url: https://github.com/shahcompbio/scgenome.git
    git_rev: master
    folder: scgenome
  - git_url: https://github.com/amcpherson/wgs_analysis.git
    git_rev: master
    folder: wgs_analysis

requirements:
  build:
    - python
    - click
    - numpy
    - matplotlib
    - pandas
    - pyyaml
    - networkx
    - dill
    - six
    - 'vcf2maf_shahcompbio'
    - 'pseudo_bulk_qc_html_report'
    - 'seaborn'
    - 'matplotlib'
    - 'packaging'
    - 'scikit-learn'
  run:
    - python
    - click
    - numpy
    - matplotlib
    - pandas
    - pyyaml
    - networkx
    - dill
    - six
    - 'vcf2maf_shahcompbio'
    - 'pseudo_bulk_qc_html_report'
    - 'seaborn'
    - 'matplotlib'
    - 'packaging'
    - 'scikit-learn'
test:
  commands:
    - vcf2maf.pl --help
    - vep --help
about:
  home: http://shahlab.ca
  summary: ''
