breakpoint_calling:
  destruct_config:
    genome_fai: test_data/align/ref_data/human/GRCh37-lite.fa.fai
    genome_fasta: test_data/align/ref_data/human/GRCh37-lite.fa
    gtf_filename: tests/ref_data/GRCh37-lite.gtf
  docker:
    destruct: singlecellpipeline/destruct:v0.0.1
    lumpy: singlecellpipeline/lumpy:v0.0.3
    samtools: singlecellpipeline/samtools:v0.0.3
    single_cell_pipeline: singlecellpipeline/single_cell_pipeline:v0.5.6
  memory:
    high: 16
    low: 4
    med: 6
  ref_data_directory: tests/ref_data
