FROM quay.io/singlecellpipelinetest/miniconda3:4.10.3

ADD . /app

RUN apt update && apt install build-essential samtools -y

RUN conda install --file /app/conda_requirements.txt
RUN pip install -r /app/pip_requirements.txt

RUN rm -rf /opt/conda/lib/python3.7/site-packages/pypeliner* && pip install git+https://github.com/shahcompbio/pypeliner.git@v0.6.2
RUN rm -rf /opt/conda/lib/python3.7/site-packages/single_cell* && pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@{git_commit}
RUN rm -rf /opt/conda/lib/python3.7/site-packages/biowrappers* && pip install git+https://github.com/shahcompbio/biowrappers.git@master

RUN pip install git+https://github.com/amcpherson/wgs_analysis.git@v0.0.2
RUN pip install git+https://github.com/shahcompbio/scgenome.git@v0.0.1
RUN pip install git+https://github.com/shahcompbio/classifycopynumber.git@v0.0.5
RUN pip install git+https://github.com/shahcompbio/mafannotator.git@master

RUN cp /app/oncokb-annotator/MafAnnotator.py /app/oncokb-annotator/AnnotatorCore.py /opt/conda/bin && chmod 777 /opt/conda/bin/MafAnnotator.py  /opt/conda/bin/AnnotatorCore.py
RUN rm -rf /opt/conda/bin/samtools