package:
  name: single_cell_pipeline_annotation
  version: '0.6.8'
source:
  git_url: https://github.com/shahcompbio/single_cell_pipeline.git
  git_rev: v0.6.8
build:
  number: 1
requirements:
  build:
    - python
  run:
    - python
    - matplotlib
    - pandas=0.25.3
    - pypdf2
    - pypeliner
    - pyyaml
    - seaborn
    - statsmodels
    - scikit-learn
    - ete3
    - cell_cycle_classifier
    - click
about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'
