package:
  name: single_cell_pipeline_annotation
  version: '0.6.34'
source:
  - git_url: https://github.com/shahcompbio/single_cell_pipeline.git
    git_rev: v0.6.34
    folder: single_cell_pipeline
  - git_url: https://github.com/shahcompbio/cell_cycle_classifier.git
    git_rev: v0.0.3
    folder: cell_cycle_classifier
build:
  number: 1
requirements:
  build:
    - python
    - click
  run:
    - python
    - drmaa
    - matplotlib
    - pandas=0.25.3
    - pypdf2
    - pypeliner
    - pyyaml
    - seaborn
    - statsmodels
    - scikit-learn
    - pytables
    #- cell_cycle_classifier=0.0.2
    - click
    - jinja2
about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'
