merge_bams:
  chromosomes:
  - '6'
  - '8'
  - '17'
  docker:
    samtools: singlecellpipeline/samtools:v0.0.3
    single_cell_pipeline: singlecellpipeline/single_cell_pipeline:v0.5.6
  max_cores: 8
  memory:
    high: 16
    low: 4
    med: 6
  one_split_job: true
  ref_genome: test_data/align/ref_data/human/GRCh37-lite.fa
  split_size: 10000000
