FROM quay.io/singlecellpipelinetest/miniconda3:4.10.3
ADD . /app


RUN conda create --name museq python=2.7
SHELL ["conda", "run", "-n", "museq", "/bin/bash", "-c"]
RUN conda install --file /app/conda_museq_requirements.yml
RUN conda install -c bioconda variantbam
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN conda install --file /app/conda_base_requirements.yml
RUN apt update && apt install samtools && rm -rf /var/lib/apt/lists/*
ENV PATH="${PATH}:/opt/conda/envs/museq/bin"

RUN pip install git+https://github.com/shahcompbio/pypeliner.git@v0.6.2
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@{git_commit}
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@master
RUN pip install pyvcf bx-python==0.8.9 numpy==1.19.5 pandas==0.25.3 --force-reinstall
RUN pip install azure-batch azure-common azure-core azure-storage-blob azure-identity
