FROM continuumio/miniconda3:4.8.2
ADD . /app


RUN conda create --name museq python=2.7
SHELL ["conda", "run", "-n", "museq", "/bin/bash", "-c"]
RUN conda install --file /app/conda_museq_requirements.yml
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

RUN conda install --file /app/conda_base_requirements.yml

ENV PATH="${PATH}:/opt/conda/envs/museq/bin"

RUN pip install git+https://github.com/shahcompbio/pypeliner.git@master
RUN pip install git+https://github.com/shahcompbio/single_cell_pipeline.git@{git_commit}
RUN pip install git+https://github.com/shahcompbio/biowrappers.git@master
RUN pip install pyvcf bx-python
